version: '3.3'

services:

  postgres:
    image: postgres
    container_name: snomedct_postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: snomedct
      POSTGRES_USER: snomedct
    volumes:
      - ./PostgreSQL/scripts:/docker-entrypoint-initdb.d
      - ./SnomedCT_InternationalRF2_PRODUCTION_20220930T120000Z:/SnomedCT:ro

  pgadmin:
    container_name: snomedct_pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: 0
