version: '3.3'

services:

  postgres:
    image: postgres
    container_name: snomedct_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: snomedct
      POSTGRES_USER: snomedct
    volumes:
      - ./PostgreSQL/scripts:/docker-entrypoint-initdb.d
      - ./SnomedCT_InternationalRF2_PRODUCTION_20220930T120000Z:/SnomedCT:ro

#  neo4j:
#    image: neo4j:3.5
#    container_name: snomedct_neo4j
#    restart: unless-stopped
#    ports:
#      - 7474:7474
#      - 7687:7687
#    volumes:
#      - ./conf:/conf
#      - ./data:/data
#      - ./import:/import
#      - ./logs:/logs
#      - ./plugins:/plugins
#    environment:
#      - NEO4J_dbms_memory_pagecache_size=1G
#      - NEO4J_dbms.memory.heap.initial_size=1G
#      - NEO4J_dbms_memory_heap_max__size=1G
#      - NEO4J_USERNAME='snomedct'
#      - NEO4J_PASSWORD='test123'
